### ISSUE TITLE
AppendRows

### ISSUE THREAD

**Issue by mrcandu** [frappe/datatable#100]
Hi
From the docs it isn't obvious what format the data should be in for `appendRows`
Tried many variations, the most obvious being: https://jsfiddle.net/mrcandu/rj8h9cw7/
But nothing is working?
Thanks
Mat.

**Comment by arun-muthuram** [comment]
> Hi
> From the docs it isn't obvious what format the data should be in for `appendRows`
> Tried many variations, the most obvious being: https://jsfiddle.net/mrcandu/rj8h9cw7/
> But nothing is working?
> Thanks
> Mat.

Hi Mat,
You are passing the data in the right format. But there is bug in code and that's why the appendRows method is not working. I have proposed a fix and raised a pull request.
[PR](https://github.com/arun-muthuram/datatable/commits/patch-2)

**Comment by ArunMuthuram** [comment]
> Hi
> From the docs it isn't obvious what format the data should be in for `appendRows`
> Tried many variations, the most obvious being: https://jsfiddle.net/mrcandu/rj8h9cw7/
> But nothing is working?
> Thanks
> Mat.

Hi Mat,
The data format you are using is right and the reason append rows are not working is due to a bug in code. I have proposed a fix and have raised a pull request. #104

**Comment by johnlandish** [comment]
has this been fixed?

**Comment by d-miles** [comment]
@netchampfaris @shariquerik could you merge @ArunMuthuram's change to fix this bug? he submitted pull request #104 (which resolves the issue) over 3.5 years ago now.

**Comment by netchampfaris** [comment]
@d-miles Thanks for tagging. Fixed now. I don't get much time to work on this. Hoping to find someone who can maintain.
