### ISSUE TITLE
Add option to provide translated labels

### ISSUE THREAD

**Issue by barredterra** [frappe/datatable#144]
<img width="367" alt="Bildschirmfoto 2021-11-05 um 17 17 38" src="https://user-images.githubusercontent.com/14891507/140543412-914d4e59-a1dd-4ae3-b07c-c2b7d5915155.png">

We should be able to provide translated labels here. Maybe that's possible already. If so, please let us know.

https://github.com/frappe/frappe/issues/13975

@netchampfaris

**Comment by hrwX** [comment]
@barredterra @netchampfaris https://github.com/frappe/datatable/pull/145
