### ISSUE TITLE
Sort of un-padded integers

### ISSUE THREAD

**Issue by agritheory** [frappe/datatable#3]
![integer_sort](https://user-images.githubusercontent.com/18033666/35599072-f3045fce-05f4-11e8-88fe-ac643ba3c780.gif)

Not sure how to solve this but I thought I'd bring it up.

**Comment by netchampfaris** [comment]
I am not sure if they should be padded or not

**Comment by agritheory** [comment]
I think I misstated the problem: these are numbers and should be sorted numerically in the index column, not alphabetically. In the latest demo it it correctly sort numerical values and the filter is gone from the index row. I think you've solved the problem but maybe differently than I was thinking.
