### ISSUE TITLE
Fixed header on scroll + Fixed column(s)

### ISSUE THREAD

**Issue by slidenerd** [frappe/datatable#37]
First of all, thank you for this awesome library, I searched through issues and did not find any mention of it. I would like to fix 2 columns on my table on the left with fixed headers, my tables have around 30 columns and 100+ rows and want to enable this feature, any suggestions are appreciated

**Comment by netchampfaris** [comment]
I have already started to implement this feature. It is in a feature branch right now. https://github.com/frappe/datatable/tree/feature-fixed-columns

**Comment by AbhiYadav96** [comment]
How to use this
