### ISSUE TITLE
Column Header / Data Widths not aligned

### ISSUE THREAD

**Issue by OneiricIT** [frappe/datatable#42]
Test on beta.erpnext.com and develop stage locally with areas utilising DataTables. 
Column widths between header and data table are out of alignment. Not certain if applicable only to ERPNext / Frappe.

![2018-08-17_15-00-13](https://user-images.githubusercontent.com/22227933/44248565-a4b01a80-a22e-11e8-8d76-47ba2ef73410.gif)

**Comment by netchampfaris** [comment]
Fixed with https://github.com/frappe/datatable/commit/a04a5a1d7c03a3084efcd48b0d28d2f416100528
