### ISSUE TITLE
Support customize visible columns as saved layout

### ISSUE THREAD

**Issue by szufisher** [frappe/datatable#44]
Currently it is possible by drag and drop columns to re-arrange columns and adjust the width, also it is possible to hide or show columns, but unfortunately the changes get lost once re-open the page again. it is desired to allow saving all the customizing: column sequence, width, show or hide, sorting, filtering as saved layout, either save such layout setting as user setting persisted to backend or saved to localstorage, and remember the last setting when next time open the same page.
Here the ALV(active List Viewer, the datatable equivalent) layout feature in SAP
![image](https://user-images.githubusercontent.com/12823863/45671699-b439c080-bb58-11e8-9969-74f9714da00b.png)
Fig 1. Layout toolbar button

![image](https://user-images.githubusercontent.com/12823863/45671713-c1ef4600-bb58-11e8-8974-841aea324e99.png)
Fig2. Layout change modal window

![image](https://user-images.githubusercontent.com/12823863/45671733-d16e8f00-bb58-11e8-9d3a-4271bb4c2c5f.png)
Fig 3: Layout save

![image](https://user-images.githubusercontent.com/12823863/45672025-a2a4e880-bb59-11e8-8cd2-c8e704e4c51a.png)
Fig4. Saved Layout list

**Comment by netchampfaris** [comment]
@szufisher These can be implemented by the consumer of DataTable library. In fact, ERPNext's Report Builder (which uses DataTable) saves the column layout for each user.

This library aims to solve only the problem of rendering large tabular data efficiently.
