### ISSUE TITLE
how can i catch editing field event? how can i get access to changed data in the table

### ISSUE THREAD

**Issue by alersenkevich** [frappe/datatable#46]
how can i catch editing field event? how can i get access to changed data in the table?? 

i changed the field, and i need to get changed data, i need to get rows in plain object format how can i do this with that lib? it's the most important thing in this and such libraries

**Comment by netchampfaris** [comment]
There is no editing event right now. You can get the changed values using 
`datatable.datamanager.getRows()`

**Comment by alersenkevich** [comment]
"There is no editing event right now" – go to the fucking notebook and work hard and make it right now 😂👨🏻‍💻🧐✍🏻

**Comment by alersenkevich** [comment]
@netchampfaris listen, data manger.getRows gives me the all rows in table, changed and not changed, it's very stupid, because I need to check what rows were changed, bad lib and I don't understand why did you do that, it is useless, I need to make most part of work myself

**Comment by netchampfaris** [comment]
@alersenkevich I am sorry it does not help you. Right now, I am only building features which are needed by our application. I plan to standardize getting data and events like you suggested. Until then, you may have to find something else.
