### ISSUE TITLE
Scrolling and Expand/Collapse issue with DataTable

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/datatable#47]
I encountered multiple issues trying to use Sales/Purchase Analytics. I already created an issue in erpnext's repo but I later realized it has more to do with DataTable so I'm posting it here too.

* When there are too many rows, another scrolling bar pops up... at around the 150 row mark
![analytics1](https://user-images.githubusercontent.com/328330/46258558-51481200-c4e6-11e8-862c-471016cb4578.gif)

* When you've clicked on a cell in a row that is near the vertical end, you cannot scroll up past a point (maybe the point at which another scrolling bar pops up)
![analytics2](https://user-images.githubusercontent.com/328330/46258571-8bb1af00-c4e6-11e8-9c0a-dab9aa2e3553.gif)

* When you collapse the last collapsible row, you cannot expand it again. And there is extra scrolling space below that point even though there aren't any more rows.
![analytics3](https://user-images.githubusercontent.com/328330/46258580-b26fe580-c4e6-11e8-9e4f-899dedd6910c.gif)

The first 2 problems can also be analyzed at https://beta.erpnext.com/desk#query-report/General%20Ledger

**Comment by netchampfaris** [comment]
@SaiFi0102 ERPNext must be on an older version of DataTable. I think it is updated now. The collapsing problem should be fixed.

The scrolling problem still exists. Will look into it.

**Comment by jodeq** [comment]
Seems to be my issue here : https://github.com/frappe/frappe/issues/6445
I think the overflow is linked to this issue
